app/__init__.py
from flask import Flask

def create_app(config_object):
    """Construct the core application."""
    app = Flask('song_recommender',static_folder = None)
    app.config.from_object(config_object)
    with app.app_context():
        # Imports
        from .views import view

        # REGISTER ROUTES
        app.register_blueprint(view)

        return app

app/views.py
from urllib.parse import quote
import random
import requests
import json

from flask import render_template, url_for, redirect, request, session, jsonify, Blueprint

from .recommendations import User, create_empty_playlist, add_playlist_tracks, get_user_id, get_track_info
from . import config


view = Blueprint("views", __name__, template_folder='templates', static_folder='static', url_prefix="/")

@view.route("/")
@view.route("/home")
def home():
    """
    Displays home page
    :return: None
    """
    return render_template('home.html')


@view.route("/authorization")
def authorization():
    """
    Redirects to Spotify authorization url
    :return: None
    """
    # Ask for user permission
    url_args = "&".join(["{}={}".format(key, quote(val)) for key, val in config.AUTH_QUERY_PARAMETERS.items()])
    auth_url = f"{config.AUTH_URL}/?{url_args}"
    return redirect(auth_url)


@view.route("/callback/q")
def callback():
    """
    Makes requests for an access token and uses it to build recommendations for the user
    :return: None
    """
    # Request refresh and access tokens
    auth_token = request.args['code']
    code_payload = {
        "grant_type": "authorization_code",
        "code": str(auth_token),
        "redirect_uri": config.REDIRECT_URI,
        'client_id': config.CLIENT_ID,
        'client_secret': config.CLIENT_SECRET,
    }
    post_request = requests.post(config.TOKEN_URL, data=code_payload)
    response_data = json.loads(post_request.text)
    access_token = response_data["access_token"]
    # Create a user object using the token
    user = User(access_token)
    # Build recommendations using saved tracks
    recommended_tracks = user.get_recommended_tracks()
    global recommended_ids
    recommended_ids = list(recommended_tracks.id)
    user_id = get_user_id(access_token)
    # Add token, tracks and user id to sessions object
    session['access_token'] = access_token
    session['user_id'] = user_id
    return redirect(url_for('views.recommendations', _external=True, _scheme="https"))


@view.route("/recommendations")
def recommendations():
    """
    Displays a playlist of recommendations to the user
    :return: None
    """
    # Generete a random sample from the recommended tracks to display as a playlist
    global recommended_ids
    track_ids = random.sample(recommended_ids, config.PLAYLIST_NUM_TRACKS)
    session['track_ids'] = track_ids
    track_info = get_track_info(track_ids, session['access_token'])
    return render_template('recommendations.html', title='Recommendations', tracks=track_info)


@view.route("/add_playlist", methods=['POST'])
def add_playlist():
    """
    Adds the playlist to the user's Spotify account
    :return: Success/Error message
    """
    # Get the user's playlist name
    name = request.form.get('name')
    playlist_id, url = create_empty_playlist(name, session['user_id'], session['access_token'])
    res = add_playlist_tracks(playlist_id, session['track_ids'], session['access_token'])
    message = f'Added playlist {name} to your Spotify account.'
    return jsonify({'message': message, 'url': url})

app/templates/home.html
{% extends "layout.html" %}
{% block content %}

<div class="container-fluid">
    <div class="row" style="padding-top: 5rem;">
        <div class="col-md-5 offset-1">
            <p style="font-size: 60pt; color:#cec7c7; word-spacing: 0%;">Spotify Recommender System</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 offset-1">
            <!-- <a class="btn btn-light" href="#" role="button">Try it out!</a> -->
            <a class="btn btn-outline-light btn-lg" href="{{url_for('views.authorization')}}" role="button"
                style="font-size:20pt;  color: #cec7c7; border-color:#cec7c7; border-width: 2pt;font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;">
                Try it out!
            </a>
            <!-- <button type="button" class="btn btn-dark">Dark</button> -->
        </div>
    </div>
    <div class="row mt-3">
        <div class="col-md-2 offset-1 ">
            <a href="https://github.com/leonleitao/spotify_recommender_system"><i class="fab fa fa-github fa-2x"
                    style="color: #cec7c7; padding-left: 2rem;"></i></a>
            <a href="https://www.linkedin.com/in/leon-leitao-655548129/"><i class="fab fa fa-linkedin fa-2x"
                    style="color: #cec7c7;padding-left: 1rem;"></i></a>
        </div>
    </div>
</div>

{% endblock %}

app/templates/layout.html
<!DOCTYPE html>
<html>

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> -->
    <!-- Bootstrap CSS -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
        integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{url_for('views.static',filename='css/main.css')}}">
    <style type="text/css">
        html,
        body {
            background-image: url("{{url_for('views.static',filename='images/background.jpg')}}");
        }
    </style>
    <link rel="icon" href="{{url_for('views.static',filename='images/icon.png')}}">
    {% if title %}
    <title>{{title}}</title>
    {% else %}
    <title>Spotify Recommender System</title>
    {% endif %}
</head>

<body>
    {% block content %}{% endblock content %}
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
    <script src="{{ url_for('views.static', filename='js/add_playlist.js') }}"></script>
</body>

</html>

app/templates/recommendations.html
{% extends "layout.html" %}
{% block content %}

<div class="container-fluid">
    <div class="row mt-4 justify-content-md-center">
        <p style="font-size: 32pt; color:#cec7c7;">Here are some tracks recommended for you...</p>
    </div>
    <div class="row">
        <div class="col-md-10 offset-1">
            <table class="table table-dark table-hover table-sm table-striped">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">TITLE</th>
                        <th scope="col">ARTISTS</th>
                        <th scope="col">ALBUM</th>
                    </tr>
                </thead>
                <tbody>
                    {% for track in tracks %}
                    <tr>
                        <th scope="row">{{loop.index}}</th>
                        <td><a href="{{track.spotify_url}}" style="color: white;">{{track.name}}</a></td>
                        <td>{{track.artists}}</td>
                        <td>{{track.album}}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3 offset-1">
            <form>
                <div class="input-group ">
                    <input type="text" class="form-control" placeholder="Enter playlist name" id='name' autocomplete="off">
                    <div class="input-group-append">
                        <button class="btn btn-dark" type="submit">Add playlist</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-md-7 text-left">
            <a href="{{url_for('views.recommendations')}}"><button class="btn btn-dark"
                    type="button">Refresh</button></a>
        </div>
    </div>
    <div class="row mt-1">
        <div class="col-md-6 offset-1" id='playlist_res' style="display:none; color:#cec7c7;"></div>
    </div>
    <div class="row">
        <div class="col-md-6 offset-1" id='url_div' style="display:none; color:#cec7c7;">
            Link to playlist: <a id='playlist_url' style="display:none; color: #cec7c7;"></a>
        </div>
    </div>
</div>

{% endblock %}